// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Data = { keypresses: bigint, left_clicks: bigint, right_clicks: bigint, middle_clicks: bigint, };
