[package]
name = "tracker"
version = "0.1.0"
edition = "2024"

[dependencies]
rdev = "0.5.3"
reqwest = {version = "0.12.23", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
tokio = "1.47.1"
ts-rs = "11.0.1"
