[package]
name = "tracker"
version = "0.1.0"
edition = "2024"

[dependencies]
rdev = "0.5.3"
reqwest = "0.12.23"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.47.1", features = ["json"] }
